CREATE TABLE solicitudesnew(
idsolicitudes int NOT NULL,
numsol int NOT NULL,
codUsu int NOT NULL,
codTipSol int NOT NULL,
idSol int NOT NULL,
fecCreacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
year char(4) NOT NULL,
pagoSolicitud int NOT NULL,
estadoSolicitud int NOT NULL,
recepcionado varchar(80) NOT NULL,
fecRecepcion DATETIME DEFAULT NULL,
encontrado int NOT NULL,
observacion varchar(255) DEFAULT NULL,
calificado varchar(255) DEFAULT NULL,
buscador varchar(255) DEFAULT NULL,
fecDespacho DATETIME DEFAULT NULL,
tipoDocumento varchar(100) DEFAULT NULL,
numFolios int DEFAULT 0,
canDocumentos int DEFAULT NULL,
fecEntrega DATETIME NOT NULL,
PRIMARY KEY(idsolicitudes)
);
